### ISSUE TITLE
Wrong image path

### ISSUE THREAD

**Issue by Dioscelestial** [ElectronicCats/CatSniffer#18]
The part of wireshark.md can't show the images cause' don't have a properly image path in the files
The issues are in ElectronicCats/CatSniffer/docs/wireshark.md

**Comment by cldrn** [comment]
Documentation is located at [https://github.com/ElectronicCats/CatSniffer/wiki](https://github.com/ElectronicCats/CatSniffer/wiki) for now. We will be generating an HTML document to include as offline documentation with the repository.
