### ISSUE TITLE
Windows 11 Issue?

### ISSUE THREAD

**Issue by Cr0wTom** [ElectronicCats/CatSniffer#19]
Hello,

I am trying to setup the SmartRF Packet Sniffer 2 with catsniffer. I can see the serial device in the control panel, but the Device configuration button on SmartRF is grayed out and the device cannot be detected. I had the latest version, but now I am on 1.8.0 of smartRF. I tried many things (I also have the SDK installed) but nothing worked. Anyone solved this issue?

Thanks

**Comment by wero1414** [comment]
Hi @Cr0wTom Did you select  the target device under the section of connected devices, to CC1352R?

This is mandatory so the SmartRF Flash Programmer 2 can be able to detect the UART bootloader

**Comment by wero1414** [comment]
https://github.com/ElectronicCats/CatSniffer/wiki/assets/foto60.jpg

**Comment by Arthulisher** [comment]
Hello Cr0wTom 

Please follow the next tutorial:
(https://github.com/ElectronicCats/CatSniffer/wiki/06.-FAQ#:~:text=What%20if%20SmartRF%20Packet%20Sniffer%202%20doesn%27t%20detect%20my%20board%3F)

Let us know any updates about your issue
Best regards...

**Comment by Cr0wTom** [comment]
All good, fixed it with firmware reflash a couple of times :)

**Comment by cldrn** [comment]
I am curious about what version did you use? Does this confirm Windows 11 support?

**Comment by Cr0wTom** [comment]
Yes this confirms Windows 11 support. 

I am using Windows 11 Pro (10.0.22000 Build 22000) and my hardware is v1.3.

**Comment by cldrn** [comment]
Did you try 1.9 on win 11?
