### ISSUE TITLE
Failed to flash a new firmware.

### ISSUE THREAD

**Issue by icabrera** [ElectronicCats/CatSniffer#21]
Hello,

I am trying to change the firmware of the CC1352.

I have succesfully loaded the sketch "Serial Passthrought with Bootloader" into the CatSniffer.

Also, I did the procedure to enter into bootloader by power off -- pressing boot button -- and then power on again. It didn't work and no LED activity.

I have noticed that CC1352 continues sending a message by UART (received by the serial passthorugh with boot) after it is supposed to be in a bootloader mode, so I think that CC1352 doesn't enter into bootloader.

The following is the received message, this is the same as when the Sniffer Firmware is working:

![image](https://user-images.githubusercontent.com/5642934/154755950-cd7464e3-e945-4b35-9338-9d1f1f959825.png)

Note: I changed the baudrate in the bootloader sketch just to be sure that CC1352 is sending the same announcement, but also tried with 500000. Changed to 500000, the message is also arriving but it is not readable:

![image](https://user-images.githubusercontent.com/5642934/154758613-639b27f7-b009-42cb-9438-bbd4f99ba92e.png)

I have been trying since I received the CatSniffer but never been acomplished. I have tried with TI and Python tools but since CatSniffer is not in bootloader mode that tools doesn't work.

![image](https://user-images.githubusercontent.com/5642934/154759717-06632c30-af2c-41fb-9d6a-6959f53deffa.png)

According to the CC13x2, CC26x2 SimpleLink Wireless MCU Technical Reference Manual, the baudrate of UART for bootloader can be synchoronized by sending 0x55 0x55.  The answer to this bytes, are the same, the announcement message.

![image](https://user-images.githubusercontent.com/5642934/154760746-54bfbc61-6515-4d00-9ec2-fd29a699d376.png)

The CatSniffer is working well with the stock firmware.

![image](https://user-images.githubusercontent.com/5642934/154755434-e969a71e-ec1b-4a85-8164-e096abce1f0d.png)

**Comment by icabrera** [comment]
Yes, I tried both ways ( button and by sketch ), and also tried a mix of two, no success.

**Comment by sabas1080** [comment]
@icabrera This product will be replaced under warranty.

**Comment by defuzzlog** [comment]
Hi. I have the same situation. Catsniffer isn't recognised in the Smart RF Sniffer 1.9 (already checked FAQ wiki github page - still no result). When I try to change firmware of the 1352 - nothnig happens. I can upload Serial Passthrought with bootloader, but 
Flash Programmer 2 doesn't see device and when I try to flash with python I get error " Timeout waiting for ACK/NACK after 'Synch (0x55 0x55)". Also when I try to enter bootloader through hardware  first pressing the “boot” button and while holding it, press and release "reset", and finally release the “boot” button - nothing happens, it didn't work and No LED activity.  Tried to run on three different computers, used different usb cables - nothing helps.
