### ISSUE TITLE
Can't flash CC1352 

### ISSUE THREAD

**Issue by defuzzlog** [ElectronicCats/CatSniffer#22]
Hi.
Catsniffer isn't recognized in the Smart RF Sniffer 1.9 (already read and applied advice from FAQ wiki GitHub page - still no result). When I try to flash the firmware of the 1352 - nothing happens. I can upload "Serial Passthrough with bootloader", but
Flash Programmer 2 doesn't see the device and when I try to flash with python I get the error " Timeout waiting for ACK/NACK after 'Synch (0x55 0x55)". Also when I try to enter the bootloader through hardware first press the “boot” button and while holding it, press and release "reset", and finally release the “boot” button - nothing happens, it didn't work and No LED activity. Tried to run on three different computers, used different USB cables - nothing helps.

**Comment by defuzzlog** [comment]
Is there any other way I can help to solve this problem? Maybe some additional data or logs are needed? And should I hope for a solution to this problem? Thanks

**Comment by sabas1080** [comment]
@defuzzlog CatSniffer is not compatible with version 1.9 of Smart RF Sniffer, you must use version 1.8 as indicated in our wiki.

when cat sniffer is in boot mode, there is no LED activity. 

To ensure that the device is in boot mode press the BOOT button without connecting to the computer, keep the BOOT button pressed and then connect the device via USB, now release the BOOT button

**Comment by defuzzlog** [comment]
> @defuzzlog CatSniffer is not compatible with version 1.9 of Smart RF Sniffer, you must use version 1.8 as indicated in our wiki.
> 
> when cat sniffer is in boot mode, there is no LED activity.
> 
> To ensure that the device is in boot mode press the BOOT button without connecting to the computer, keep the BOOT button pressed and then connect the device via USB, now release the BOOT button

Just checked in Smart RF Packet Sniffer 1.8 - it is doesn't detect Catsniffer.

Folowed you steps - press Boot and hold it until device connected via USB, release it after connection via usb. Doesn't help. It still can't find cc1352 over python cmd or flash programmer

**Comment by defuzzlog** [comment]
> Hello @defuzzlog Could you share pictures of your COM port on the device manager? in order to see if your system is detecting your board.

Without catsniffer: [https://disk.yandex.ru/i/Fq3Yyq3xIx76dw](url)
With catsniffer: [https://disk.yandex.ru/i/Zy41JxDXJknXYQ](url)

**Comment by Arthulisher** [comment]
Hello, @defuzzlog Could you describe or share a video of the Led 4 behavior when you plug the USB, Please? Also, could you upload to the cat sniffer the serial passthrough and describe the behavior too?

**Comment by defuzzlog** [comment]
> Hello, @defuzzlog Could you describe or share a video of the Led 4 behavior when you plug the USB, Please? Also, could you upload to the cat sniffer the serial passthrough and describe the behavior too?

[https://youtu.be/QrYOePBE02g](url)

**Comment by Arthulisher** [comment]
Hello @defuzzlog  thanks for the video, could you upload the SerialPassthrough.ino please and describe the behavior of LED D4, please?

**Comment by Arthulisher** [comment]
Hello @defuzzlog 

It seems to be that your CC1352 chips are bricked, could you send us an e-mail at the next address support2@electroniccats.com, please?  
We are going to continue your issue by e-mail.

**Comment by alphafox02** [comment]
Was this ever resolved, if so how was the CC1352 flashed?
