### ISSUE TITLE
CC1352 and LoRa compatibility

### ISSUE THREAD

**Issue by reiniercoetzer** [ElectronicCats/CatSniffer#25]
Hi Electronic Cats (@Liars126) !

I recently came across your CatSniffer, which is a pretty handy device!

I am currently doing some research on LoRa compatible MCUs and officially it seems as though TI does not support LoRa. However, I also read that the CC1352 (which you guys are using) supports Amazon Sidewalk, which is based on LoRa (perhaps only the protocol?).

For the CatSniffer, I assume you use the Semtech SX1262 for LoRa, but since you are also familiar with the CC1352, do you perhaps know if this MCU is somehow compatible with the LoRa PHY?

Thanks in advance!

Best regards,
  Reinier

**Comment by jazhe** [comment]
Hello @reiniercoetzer!

Thank you for the interest in our products and your feedback, is much appreciated!

Yes, we use Semtech SX1262 for LoRa and unfortunately CC1352 is not compatible with LoRa.

Thank you for you patience. Feel free to get back to us if you have any further queries.

Kind regards, 
Electronic Cats Support Team

**Comment by reiniercoetzer** [comment]
Many thanks for your feedback! 

Maybe useful for someone else in the future (you guys know this of course):

I also got some information directly from TI and as expected the CC1352 PHY is not compatible with the standard LoRa modulation, i.e. LoRa uses chirp spread spectrum (CSS) technology, whereas the CC1352 PHY can do spread spectrum using GFSK, which is more applicable to Amazon Sidewalk for which the CC1352 is supported.

**Comment by jazhe** [comment]
Hi @reiniercoetzer!

Thank you so much for your feedback, we appreciate it!

We are very grateful that you bring this to our attention. These types of feedback help us improve our platform and our products! Feel free to get back to us if you have any further queries or feedback.

Hope you have an amazing day!
Kind regards,
Electronic Cats Support Team
