### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by iamapentester** [ElectronicCats/CatSniffer#26]
This project is really hard to get started with. 

The github contains a lot of firmwares and 3d Prints files but not really any informations of how to install the firmware and use the stick. 

Could you make a quick-start guide - i am running Linux and bought this stick because it was linux compatible but have still not figured out how to get it up and running - wireshark plugins is only for windows :/

**Comment by IvanAmg** [comment]
Hello @iamapentester!
Have you already visited our official Wiki?
![image](https://user-images.githubusercontent.com/96195073/185204069-8fdde84d-4446-4156-9591-91c0d6ae04ae.png)
There you'll find our quickstart guide.
![image](https://user-images.githubusercontent.com/96195073/185204451-1d20a61d-1b75-417a-bcfb-02cfc0bc5fd8.png)
Let me know if something else is missing!

**Comment by iamapentester** [comment]
ah ! pages .. i missed them - thanks.

**Comment by IvanAmg** [comment]
No worries at all!
