### ISSUE TITLE
SmartRF can't detect CatSniffer

### ISSUE THREAD

**Issue by gilmarwsr** [ElectronicCats/CatSniffer#27]
SmartRF can't detect CatSniffer, is there any troubleshoot script? How can I check if the hardware (bought at DEFCON30) is fine?

I've tried some firmware scripts just to check the communication:
![image](https://user-images.githubusercontent.com/10632916/186001770-ff330d62-fc22-47fc-8033-0605cb43734e.png)

I've changed the timeout on the python script :

![image](https://user-images.githubusercontent.com/10632916/186005083-01d703fd-54e0-4ee3-8f32-95b451caaac5.png)

I'm switched from MacOS to an  Windows 8 on Parallels ... and the drivers seems to haven't been installed:
![image](https://user-images.githubusercontent.com/10632916/186023489-4d214ed7-6e3c-42ce-87bd-77694a23e833.png)

**Comment by IvanAmg** [comment]
Hello @gilmarwsr !
May I ask if the LED4 is blinking when connected to your PC?
If so, please try to enter on bootloader mode.
To enter this mode, first press the “boot” button, and while holding it, press and release "reset", and finally release the “boot” button.
LED4 should now stop blinking.
Now you should be able to connect your board.
However, please let me know if the issue persists!

**Comment by gilmarwsr** [comment]
> Hello @gilmarwsr !
> May I ask if the LED4 is blinking when connected to your PC?
Yes It is.

> If so, please try to enter on bootloader mode.
> To enter this mode, first press the “boot” button, and while holding it, press and release "reset", and finally release the “boot” button.
> LED4 should now stop blinking.
The LED4 stopped to blink so all LEDs are now off.

> Now you should be able to connect your board.
> However, please let me know if the issue persists!
Unfortunately the problem persists.

**Comment by IvanAmg** [comment]
The CatSniffer has a similar chip as our DAPCat.
Please, try installing this driver https://zadig.akeo.ie/ if using windows 8.
And using MacOS, please specify your port when running the python script.
Let me know if the issue persists!

**Comment by gilmarwsr** [comment]
> The CatSniffer has a similar chip as our DAPCat.
> Please, try installing this driver https://zadig.akeo.ie/ if using windows 8.
> And using MacOS, please specify your port when running the python script.
> Let me know if the issue persists!

I tried my best to install multiple drivers, change COM ports and etc... now, my CatSniffer LED4 is blinking and this two drivers are listed:
![image](https://user-images.githubusercontent.com/10632916/186723973-73fb3a8d-1a15-4dff-80f7-0aad0d208886.png)

But, the SmartRF (v 1.8.0) still can't detect the CatSniffer...

![image](https://user-images.githubusercontent.com/10632916/186724204-b9448907-3ddf-4bca-aa52-b22ef0d34c62.png)

**Comment by IvanAmg** [comment]
Thanks a lot for all the information!
Let's try troubleshooting with the python script, as this is the easiest way to get more information about the issue.

First, please try to upload the SerialPassThroug with bootloader.ino as this guide says https://github.com/ElectronicCats/CatSniffer/wiki/02.-Flashing-firmwares-(Bootloader-Modes-and-Software)#bootloader-mode-through-firmware:~:text=CC1352-,Bootloader%20mode%20through%20firmware,-To%20enter%20in

Then, try to enter bootloader mode.
To enter this mode, first press the “boot” button, and while holding it, press and release "reset", and finally release the “boot” button. LED4 should stop blinking by now.

After that, please, use the python cc2538-bsl.py -p "port" command on your terminal, where "port" is the port number of where the CatSniffer is connected to your PC, this may change depending on your OS.

Let me know if the issue persists!

**Comment by gilmarwsr** [comment]
@IvanAmg 

I've tried to upload via python:
![image](https://user-images.githubusercontent.com/10632916/186915267-bc10c48f-ef4b-4ef1-ac7a-5beb12f2e293.png)

I also tried via SmartRF Flash Programmer 2 (ver 1.8.2)

![image](https://user-images.githubusercontent.com/10632916/186915508-9d04eda2-e3e8-4b7f-829a-c7a3ae93d9dd.png)

To be clear, in this SmartRF Flash section its an item (item 2) 
> 2. Upload the firmware SerialPassThroughwithboot.ino to your CatSniffer.

I really don't understand if this is an instruction to me to upload the file to somewhere (how?) or this is what we gonna do now... (I'm Brazilian so English is not my first language).

**Comment by IvanAmg** [comment]
@gilmarwsr In order to upload the SerialPassThroughwithboot.ino to your CatSniffer, you may need to use the Arduino IDE.
To install our board cores and support, please follow this part of the wiki.
https://github.com/ElectronicCats/CatSniffer/wiki/02.-Flashing-firmwares-(Bootloader-Modes-and-Software)#bootloader-mode-through-firmware:~:text=J%2Dlink%20method.-,Arduino%20IDE%20and%20Electronic%20Cats%20Board%20Support,-The%20Arduino%20Integrated
This .ino file is available right here.
https://github.com/ElectronicCats/CatSniffer/tree/master/firmware/SAMD/SerialPassthroughwithboot
Please, use the Arduino IDE to upload the SerialPassthroughwithboot.ino, and try to connect again with the python script.
Let me know if the issue persists!

**Comment by gilmarwsr** [comment]
@IvanAmg 
I've uploaded SerialPassThroughwithboot.ino

Sketch uses 9432 bytes (3%) of program storage space. Maximum is 262144 bytes.
Global variables use 2124 bytes of dynamic memory.
Atmel SMART device 0x10010094 found
Device       : ATSAMD21E17D
Chip ID      : 10010094
Version      : v1.1 [Arduino:XYZ] Jul 24 2021 11:48:53
Address      : 8192
Pages        : 1920
Page Size    : 64 bytes
Total Size   : 120KB
Planes       : 1
Lock Regions : 16
Locked       : none
Security     : false
Boot Flash   : true
BOD          : true
BOR          : true
Arduino      : FAST_CHIP_ERASE
Arduino      : FAST_MULTI_PAGE_WRITE
Arduino      : CAN_CHECKSUM_MEMORY_BUFFER
Erase flash
done in 0.577 seconds

Write 9784 bytes to flash (153 pages)
[==============================] 100% (153/153 pages)
done in 0.087 seconds

Verify 9784 bytes of flash with checksum.
Verify successful
done in 0.032 seconds
CPU reset.

But the python script ,or  SmartRF Flash Programmer 2, doesn't work.
Now, when I connect my board all LEDs are off, which I think its okay, right?
I can reset the CS1352P by press the reset button (and the LED4 starts to blink).
I've tried python script on boot settings (all LEDs off).

**Comment by IvanAmg** [comment]
Hi! @gilmarwsr 
Let's try a different thing.
On the [SerialPassthrough.ino](https://github.com/ElectronicCats/CatSniffer/blob/master/firmware/SAMD/SerialPassthrough/SerialPassthrough.ino) example, you'll see these baud rate code lines.
```
//unsigned long baud = 921600;//Baud for SmartRF Sniffer 2 also works with Smart RF Flash Programmer 2
unsigned long baud = 2000000;//Baud for Sniffle
//unsigned long baud = 115200;//Baud for Zigbee2MQTT
```
Please, comment the baud for sniffle and erase the // from Baud for SmartRF. Should look something like this.
```
unsigned long baud = 921600;//Baud for SmartRF Sniffer 2 also works with Smart RF Flash Programmer 2
//unsigned long baud = 2000000;//Baud for Sniffle
//unsigned long baud = 115200;//Baud for Zigbee2MQTT
```
Upload it to your board with Arduino IDE.
After that please, try to connect it again with SmartRF.
If the issue persists, please try the python script with your Mac OS pc, as the compatibility with Windows 8 is not fully tested yet.
Make sure that the command specifies the COM where you're connecting your CatSniffer to your Mac.

**Comment by gilmarwsr** [comment]
@IvanAmg 
Let me update the whole situation...
I was able to use the python script (only in MacOs), unfortunately, it seems to be a problem with windows 8 compatibility. I will try SmartRF as soon as possible with a fresh Windows 10 installation. 
Is there any chances to use Wireshark on MacOS with CatSniffer?

**Comment by IvanAmg** [comment]
@gilmarwsr 
I'm glad that it is working now!
We'll include that compatibility issue in our wiki, thanks for letting us know about it.
There's a small guide about Wireshark using windows, it seems like Mac OS hasn't been tested yet, if you would like to try and share your results with us, that would be amazing!
