### ISSUE TITLE
ElectronicCats - Bricked Card? Wrote incorrect version of firmware

### ISSUE THREAD

**Issue by Dlat** [ElectronicCats/CatSniffer#47]

**Comment by YoshiDev22** [comment]
Hello Dlat,

Thank you for contacting us.

If you loaded a different firmware version, it can brick the board and it would be necessary to reprogram it with a J-Link, please try the process again or program it in another way, but if following the steps in our guide, it still can not load the correct firmware, a J-Link will be necessary.

Let us know your findings.
Kind regards,
Electronic Cats Support Team
