### ISSUE TITLE
Flashing failed to verify, stuck. 

### ISSUE THREAD

**Issue by lukeswitz** [ElectronicCats/CatSniffer#48]
Board v2.0 - Linux & Windows

Steps to flash
- Flash arduino serialtoboot
- Successfully got to step in python flash where it says to press reset after testing the port. 
- Pressed reset, next command failed with the ACK/Synch error. 
- Entered flash mode again manually with button combo
- Performed the command with the sniffer_fw.hex in the 1352r bin folder (the name in the docs doesn’t exist in the repo). 
- Erased and flashed, verifying then ERROR timeout waiting after Get CRC32
- Led 2 now flashes whenever connected and it won’t go back into flash or boot mode.
- Holding boot and plugging it in causes all 4 leds to blink in succession. 

Did I brick it already?

**Comment by Marcelol52** [comment]
Hello Luke!

Thank you for contacting us!

I am sorry to hear you are having issues with you Cat Sniffer. To better understand your situation can you share the following information with us:

- What Operating System and version are you using? Linux distribution?
- Are you following this steps on windows or linux?
- Did the borad work before? 
- Is it working/recognized in the Arduino IDE?
- Please connect your board and send me a screenshot of the Device Manager of the computer (with “Ports” open) if using Windows.
- Video of the behavior of the LEDs
- Photos of both sides of the board
- If you can, please share with us your invoice to this email address: support6@electroniccats.org

Kind regards,

Marcelo Arredondo
Electronic Cats

**Comment by lukeswitz** [comment]
I flashed the original ino and it performs as when it arrived. So I think there's hope...

What Operating System and version are you using? Linux distribution?
- Debian & Windows 10 

Are you following this steps on windows or linux?
- Tried linux, did not work, flashed the catsnifferLora back and it operated as it did when it arrived. I then switched to a windows environment to use the TI tools as outlined. With the `serialpassthough.ino` without boot and the baud set for the RF 2, I get it showing up and starting in Packet Sniffer2  v1.8 however it isn't seen in Wireshark and no data is captured by way of direct from Sniffer2.

Did the borad work before?
- Not sure.. it wasn't recognized as any type of device using Wireshark before attempting to flash. Same output when it arrived

Is it working/recognized in the Arduino IDE?
- Yes, it shows as a COM port in Windows and a dev/tty/ACM0 in linux

Please connect your board and send me a screenshot of the Device Manager of the computer (with “Ports” open) if using Windows
- These look exactly the same as in the closed issue, the board and the Ports, COM5 is how it's recognized. 

Video of the behavior of the LEDs
- They go from 1 to 4 and repeat when the passthrough with boot and boot button held on poweron 

Photos of both sides of the board
- Exactly as shown in closed issue of same, its the 2.0

If you can, please share with us your invoice to this email address: [support6@electroniccats.org](mailto:support6@electroniccats.org) 
- Why?

**Comment by Marcelol52** [comment]
Hi Luke,

Thanks for sharing the information with me.

I will try to replicate the issue you are expriencing on my end and update you as soon as I find a solution. Also, can you point me to where you raised your previous issue? We cannot find it in our closed issues for the Cat Sniffer.

Kind regards,

Marcelo Arredondo
Electronic Cats

**Comment by lukeswitz** [comment]
Thanks! https://github.com/ElectronicCats/CatSniffer/issues/46#issuecomment-1681218535

**Comment by Marcelol52** [comment]
Hi Luke, 

One more question, what version of WireShark are you using? 

Thanks and regards,

Marcelo Arredondo
Electronic Cats

**Comment by lukeswitz** [comment]
> Hi Luke,
> 
> One more question, what version of WireShark are you using?
> 
> Thanks and regards,
> 
> Marcelo Arredondo Electronic Cats

Stable Release: 4.0.8

**Comment by Marcelol52** [comment]
Hi Luke,

If you were following our tutorial to use TI's Packet Sniffer with Wire Shark, download satable version [3.0.14 of WireShark](https://2.na.dl.wireshark.org/win32/all-versions/). You will need to unisntall both programs before installing this version of WireShark or Packet Tracer might not detect WireShark.

Thanks and regards,

Marcelo Arredondo
Electronic Cats

**Comment by lukeswitz** [comment]
I must have missed that- Thanks for all the help and quick replies. Loving all the toys from DEFCON. Keep being awesome.

**Comment by lukeswitz** [comment]
While it did recognize Wireshark on Sniffer install the problem remains. Can you advise which .ino to flash? Putting it into boot loader mode with the ino or buttons leads to: 
`ERROR: Timeout waiting for ACK/NACK after 'Get ChipID (0x28)' ` and when its not in bootloader mode:
`ERROR: Timeout waiting for ACK/NACK after 'Synch (0x55 0x55)'  ` is that anything you've encountered? Not able to flash using Ti flash either, just error.

**Comment by Marcelol52** [comment]
Hi Luke,

I hope you are having a good day!

The fact that WireShark was detected by the Packet Sniffer is a good sign. You board's chip cc1352 already comes flashed from the factory, there is no need to change the firmware. To use your board with Packet Sniffer and Wire shark, you only need to flash [SerialPasstrough.ino](https://github.com/ElectronicCats/CatSniffer/tree/master/firmware/V3.x/RP2040/SerialPasstrough) to the RP2040 using the Arduino IDE. You can follow the steps shown [here](https://github.com/ElectronicCats/CatSniffer/wiki/04.-Supported-software#smartrf-packet-sniffer-2). Check that the board works like that. If later you need help flashing firmware to the cc1352 for another specific application we can check that together. 

Kind regards,

Marcelo Arredondo
Electronic Cats

**Comment by lukeswitz** [comment]
I wanted to flash your custom fw, but the tool does as above when using the ino you mention. Led 2 steady flash, nothing working in wireshark and sniffer can’t see the device. When serialpassthough.ino is uploaded it can communicate with rf sniffer but isn’t recognized by wireshark or log any packets in out modes.

**Comment by Marcelol52** [comment]
Hi Luke,

When you downloaded Wire Shark, did you create the [Desktop Shortcut](https://github.com/ElectronicCats/CatSniffer/wiki/04.-Supported-software#smartrf-packet-sniffer-2-setup) with the requiered properties ("C:\<path>\Wireshark.exe" -i\\.\pipe\tiwspc_data -k)? This will set up the pipe from TI's Packet Sniffer to WireShark.

Kind regards,

Marcelo Arredondo
Electronic Cats

**Comment by lukeswitz** [comment]
I did allow that on install, and it's plugins recognized in Wireshark. The issue I am concerned with is the inability to flash the CC chip after that first go I describe in first comment and subsequent errors in bootloader mode. Seems I borked the fw

**Comment by Marcelol52** [comment]
Hi Like, 

If you are able to use WireShark now with your board and see the sniffed packets, it means your board is working fine. Give me some time to try and flash the firmware you were trying to load and see if I get any similar errors or find a solution.

**Comment by lukeswitz** [comment]
>does your board have? P or R?

Crap, it's a P and I flashed the R sniffer hex..

**Comment by lukeswitz** [comment]
And I am not able to capture any traffic, likely because of the bad choice to flash that. Is there a way back from this without a physical programmer?

<img width="741" alt="Screenshot 2023-09-06 at 4 41 30 PM" src="https://github.com/ElectronicCats/CatSniffer/assets/10099969/60e6d527-5dec-4fd0-9bb1-1fc8ae93d233">

**Comment by Marcelol52** [comment]
Hi Luke,

The only way right now to programm the board if it was bricked is using a J-link. We have a tutorial on our Wiki about this. I suggest you look into the J-link EDU, it is the most affordable one. The programmer might also be useful for your future projects. We are currently working on tutorials to reprogram bricked boards using Raspberry Pico or Raspberry PI, but they will come out some time in the future. 

Can you share with me photos of both sides of your board?

**Comment by lukeswitz** [comment]
That’s what I suspected. Nah I’m good. It’ll go in the dead bin for now. Thanks for the help. A thought though; don’t lead people directly to the bootloader on the readme- nobody sees the wiki unless you explicitly point it out seeing as there’s half a dozen bricked boards in these closed comments. The docs are good but jump back and forth between linux macOS and windows. Concise instructions on the readme.md would be beneficial. 

It says it comes without firmware on the chip this is why I flashed it. And I imagine that’s why others did also.

**Comment by Marcelol52** [comment]
Hi Luke,

Thanks for your feedback, we value our customer a lot and apreciate their input. We will take your advice into account for updating our docs. The best of luck on your future projects.

Kind regards.

**Comment by cldrn** [comment]
Another option is to ship us the hardware or meet us at a security conference and we will re-flash it for you. We are usually at most major conferences in America. When will you attend your next CON?

**Comment by lukeswitz** [comment]
> Another option is to ship us the hardware or meet us at a security conference and we will re-flash it for you. We are usually at most major conferences in America. When will you attend your next CON?

Not until next year. This is a very kind offer and I’d take you up on it. Are there any v3 boards available or in prod? I can email you if that’s better.

**Comment by jazhe** [comment]
Hello @lukeswitz!
Please email us to support@electroniccats.com to start the process. Yes, we do have V3 boards available. We look forward to hearing from you.

**Comment by lukeswitz** [comment]
Done and done and ✅

**Comment by Marcelol52** [comment]
Hi Luke, 

Just to let you know that we have received your old board (v2.0) and will send you the new (v3.1) one soon.

**Comment by lukeswitz** [comment]
Thanks so much for all the support and service.
