### ISSUE TITLE
Does the official Sniffle work with CatSniffer?

### ISSUE THREAD

**Issue by victorhooi** [ElectronicCats/CatSniffer#75]
Sorry if this is a stupid question - but does the official Sniffle project work with the CatSniffer? Or do you need to patch it to work with the CatSniffer device?

I saw that there's downloadable CatSniffer firmware files here (v1.1.0) that was released January 19, 2024:

https://github.com/ElectronicCats/CatSniffer-Firmware/releases/

And one of those is a CatSniffer Sniffle firmware file ([sniffle_CC1352P_7_v1.7.hex](https://github.com/ElectronicCats/CatSniffer-Firmware/releases/download/board-Iv3.x-v1.1.0/sniffle_CC1352P_7_v1.7.hex)).

There also seems to be a ElectronicCats fork of the Sniffle - although it's last updated 3 years ago:

https://github.com/ElectronicCats/Sniffle

If you look at the official NCCGroup Sniffle repo - it's a bit confusing, because they also have a version 1.1.0 - but that was released June 3, 2024 (i.e. 4 days ago):

https://github.com/nccgroup/Sniffle/releases

Can we use those releases on your board? Or is there somewhere we can see the differences?a

**Comment by cschweers** [comment]
@victorhooi try to expand your reading skills, the Sniffle release version from June 3rd is **1.10.0** ...

**Comment by Marcelol52** [comment]
Hi @victorhooi, we do some modification to the tool to be able to compile it for the CatSniffer. Right now the [latest version](https://github.com/ElectronicCats/CatSniffer-Firmware/releases/tag/board-v3.x-v1.1.0) compiled for the CatSniffer is version 1.7.

**Comment by victorhooi** [comment]
@Marcelol52 Ah got it - thanks for explaining!

I believe Sniffle 1.7 is quite old (2022):

https://github.com/nccgroup/Sniffle/releases/tag/v1.7

Do you know if your modifications to get it to work on the CatSniffer are available anywhere online?

And would it be quite difficult to get the recent versions of Sniffle (e.g. [Sniffle 1.10.0](https://github.com/nccgroup/Sniffle/releases/tag/v1.10.0)) working on the CatSniffer?

Also - I previously purchased a CatSniffer V2 - is there much advantage to ordering a CatSniffer V3 as well?

**Comment by Marcelol52** [comment]
@victorhooi We will close this issue now, however, please feel free to reach out to us again in case you have further suggestions, encounter an issue, or you would like to contribute.
