### ISSUE TITLE
LoRa sniffing - how to? 

### ISSUE THREAD

**Issue by gertrudem** [ElectronicCats/CatSniffer#77]
I currently have a CatSniffer V3.1. I have been able to use pycatsniffer for Zigbee sniffing without an issue, I am liking it so far.

I am a beginner when it comes to using technology like this, so I hope you will be patient with me. I had a few questions about sniffing LoRa with CatSniffer.

The device is the same as it arrived from factory, although I did flash the SerialPassthroughwithboot UF2 firmware.

I noticed that CatSniffer has a chip dedicated for LoRa. However, there seems to be very little information on how to actually use it (LoRa-CLI). Can you please help me out in using the LoRa-CLI sniffer tool? How do I run it, will I be needing to use Arduino IDE?

Also, I saw that ElectronicCats sells the CatWAN USB stick which is capable of sniffing LoRa and LoRaWAN. I am not sure if this is the right place to ask, please let me know if otherwise.

When it comes to sniffing LoRa/LoRaWAN, are there any reasons as to why someone should get CatSniffer rather than CatWAN, or vice versa?

For feedback, I would love to see an update to the LoRa sections of the Wiki. Seeing some examples of the LoRa sniffer in use would be helpful.

Thank you

**Comment by Marcelol52** [comment]
Hi there, the LoRa-CLI is documented on one of our other repositrories. You can check how to use it following the steps mentioned [here](https://github.com/ElectronicCats/CatWAN_USB_Stick/wiki/5.-Examples#using-lora-sniffer-tool). Right now we do not have a precompiled version of that firmware for the CatSniffer, but we are currently working on it and it should be up in a few days. When the UF2 is ready, you should be able to upload it to the board following the smae preocess used for the SerialPassthrough. The process to upload the firmware using the Arduino IDE is also documented in the CatWAN-USB-Stick repository, you can check that [here](https://github.com/ElectronicCats/CatWAN_USB_Stick/wiki/4.-First-Steps-with-CatWAN-USB-Stick). You need to use the steps for the RP2040 version. 

Regarding your other questions, the CatSniffer is a more powerful and capable device. It works for many protocols, not just LoRa, as the CatWAN does.

We really appreciate your feedback and will be taking it into account for future updates for the Wiki. Comments like yours help us keep growing.

**Comment by cldrn** [comment]
You can follow along the progress here: https://github.com/ElectronicCats/CatSniffer-Tools/issues/23

As Marcelo mentioned, you may use the same software, but we are also adding a custom sniffer with channel hopping for the catsniffer.

**Comment by Marcelol52** [comment]
Hi @gertrudem, we will close this issue for now. Do not hesitate to contact us again if you have any other questions or issues.

**Comment by Marcelol52** [comment]
Hi @gertrudem, we will close this issue for now. Do not hesitate to contact us again if you have any other questions or issues.

**Comment by gertrudem** [comment]
Hello,

Thank you for your responses.

I was wondering, is there an ETA for the LoRa-CLI firmware UF2 for CatSniffer? I looked at the link cldrn posted, but there did not seem to be much activity. I would prefer not using the Arduino IDE method, but no worries if it will take time! I do not mean to rush.

Thank you

**Comment by Marcelol52** [comment]
@gertrudem On our [latest release](https://github.com/ElectronicCats/CatSniffer-Firmware/releases/tag/board-v3.x-v1.1.0) there are two LoRA_CLI firmwares that you can use. They are still on a testing stage but you can start working with them.

**Comment by gertrudem** [comment]
I completely missed that, thanks so much!
